### ISSUE TITLE
Feature Request: enable an option to exclude predefined icons

### ISSUE THREAD

**Issue by cheeze2000** [nvim-tree/nvim-web-devicons#102]
Is there currently a way to disable the use of the predefined icons? I was thinking maybe it can be an option during the setup.
```lua
require('nvim-web-devicons').setup {
  override = {},     -- we define all our icons here
  predefined = false -- use none of the predefined icons
}
```
The reason for this is so that I can define a universal default icon for every single filetype. Can you suggest a better approach perhaps?

**Comment by kyazdani42** [comment]
not sure why you'd want to do this though :)
but it could be done somehow like this:
```lua
local icons = require'nvim-web-devicons'.get_icons()
local new_icons = {}
for ft, i in pairs(icons) do
  new_icons[ft] = {
    icon = "X",
    color = "#ffffff",
    cterm_color = 255,
   name = i.name
  }
end
require'nvim-web-devicons'.set_icon(new_icons)
```
or something like that

**Comment by gegoune** [comment]
Closing, feel free to reopen if provided solution is not adequate.
