### ISSUE TITLE
Python File Icons Not Theming

### ISSUE THREAD

**Issue by karimlevallois** [nvim-tree/nvim-web-devicons#106]
Hi there

It seems that the icons for Python files are not theming in response to the set colorscheme. No matter what colorscheme I apply the icons are showing as bright yellow.

Are you aware of any issues with icons not theming correctly?

**Comment by kyazdani42** [comment]
Icons have fixed colors that's why they don't theme correctly. You could override the highlight group for the icon depending on the theme you are using.
