### ISSUE TITLE
add prettier icon

### ISSUE THREAD

**Issue by jose4125** [nvim-tree/nvim-web-devicons#127]
add prettier icon to .prettierrc or .prettierrc.js and .prettierignore files

**Comment by kyazdani42** [comment]
please make a PR :)

**Comment by Novelier-Webbelier** [comment]
Hello! I have a same issue. So, I want to create prettier and eslint icon. But I do not know how to create icons. How do I create icons?

Here is the Files that I will create. (I will create just prettier and eslint icon.)

- Prettier
  - `.prettierrc`
  - `.prettierrc.js`
  - `.prettierrc.cjs`
  - `prettierrc.config.js`
  - `prettier.config.cjs`
  - `.prettierrc.json`
  - `.prettierrc.yml`
  - `.prettierrc.yaml`
  - `.prettierrc.json5`
  - `.prettierrc.toml`

- Eslint
  - `.eslintrc.js`
  - `.eslintrc.cjs`
  - `.eslintrc.yaml`
  - `.eslintrc.yml`
  - `.eslintrc.json`

###### This is my first issue on Github!

**Comment by kyazdani42** [comment]
you should allow patched fonts to have those, i don't know how that works exactly, check on https://github.com/ryanoasis/nerd-fonts
