### ISSUE TITLE
Latest commit incompatible with tabline

### ISSUE THREAD

**Issue by psicho2000** [nvim-tree/nvim-web-devicons#172]
The currently latest [commit 520776f](https://github.com/nvim-tree/nvim-web-devicons/commit/520776f30a3b39ed56402bffbdae57549e778b40) leads to loading issues when used with tabline (tabline itself makes use of nvim-web-devicons):

```
E5108: Error executing lua ....vim/plugged/nvim-web-devicons/lua/nvim-web-devicons.lua:1682: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        ....vim/plugged/nvim-web-devicons/lua/nvim-web-devicons.lua:1682: in function 'setup'
        ....vim/plugged/nvim-web-devicons/lua/nvim-web-devicons.lua:1690: in function 'get_icon'
        /home/user/.vim/plugged/tabline.nvim/lua/tabline.lua:308: in function 'get_props'
        /home/user/.vim/plugged/tabline.nvim/lua/tabline.lua:281: in function 'new'
        /home/user/.vim/plugged/tabline.nvim/lua/tabline.lua:591: in function 'tabline_buffers'
        /home/user/.vim/plugged/tabline.nvim/lua/tabline.lua:968: in function </home/user/.vim/plugged/tabline.nvim/lua/tabline.lua:96
3>
```

## Reproduction

* Checkout the above commit
* Install [tabline](https://github.com/kdheepak/tabline.nvim) and load that plugin:
```
lua << END
    require('tabline').setup()
END
```

## Workaround
a) use former [commit 9061e2d](https://github.com/nvim-tree/nvim-web-devicons/commit/9061e2d355ecaa2b588b71a35e7a11358a7e51e1)

b) do not use tabline

**Comment by T-727** [comment]
Could you provide the output of `nvim --version` please?

**Comment by psicho2000** [comment]
```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by T-727** [comment]
As suspected, you are using an outdated version of neovim.
The latest stable release currently is 0.8
And the release which provides the api used in the commit is 0.7

**Comment by psicho2000** [comment]
Thanks for the answer, that closes the issue.

**Comment by alex-courtis** [comment]
Thanks for looking into this @T-727
