### ISSUE TITLE
Does not work with alacritty

### ISSUE THREAD

**Issue by nevzatseferoglu** [nvim-tree/nvim-web-devicons#180]
<img width="334" alt="Screen Shot 2022-12-13 at 15 28 03" src="https://user-images.githubusercontent.com/43863606/207318223-8e600b69-09f9-4291-9d70-0f4e113a231c.png">

Here is the view.

**Comment by alex-courtis** [comment]
Please ensure that you have a patched font correctly configured. See https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#icons-not-correctly-shown

**Comment by nevzatseferoglu** [comment]
Thanks for the answer, I resolved the issue. My font was not based on `https://www.nerdfonts.com/`, then I updated. Closing issue!

**Comment by nevzatseferoglu** [comment]
Fonts should be based on https://www.nerdfonts.com/. I updated with it then the icons appear.
