### ISSUE TITLE
change color icons

### ISSUE THREAD

**Issue by Ethanol48** [nvim-tree/nvim-web-devicons#182]
I wanted to change some icons, that works just fine the only thing is that now there are white, and I'm trying to put the colors, but they don't change, am I doing it right ?

```lua
require'nvim-web-devicons'.setup{

    override = {
        go = {
            icon = " ",
            color = "#00ADD8"
        },
        css = {
            icon = "",
            color = "#3261A6"
        },
        sh = {
            icon = "",
            color = "#2B3F5D"
        },
        html = {
            icon = "",
            color = "#DD6C3D",
        }
    }
}
```

**Comment by Ethanol48** [comment]
I also tried this in my init.lua, the icon change work but the color doesn't

```lua
local nvim_web_devicons = require "nvim-web-devicons"

local current_icons = nvim_web_devicons.get_icons()
local new_icons = {}

for key, icon in pairs(current_icons) do
    icon.color = "#ff0088"
    icon.cterm_color = 198
    new_icons[key] = icon
end

nvim_web_devicons.set_icon(new_icons)
```

**Comment by alex-courtis** [comment]
Do you have `&termguicolors` set?

You can use `cterm-color` if you don't use it.

https://github.com/nvim-tree/nvim-web-devicons/blob/05e1072f63f6c194ac6e867b567e6b437d3d4622/lua/nvim-web-devicons.lua#L168

**Comment by Ethanol48** [comment]
> Do you have `&termguicolors` set?
> 
> You can use `cterm-color` if you don't use it.
> 
> https://github.com/nvim-tree/nvim-web-devicons/blob/05e1072f63f6c194ac6e867b567e6b437d3d4622/lua/nvim-web-devicons.lua#L168

Yes, I have set it to true,

```lua
vim.opt.termguicolors = true
```

**Comment by alex-courtis** [comment]
Which plugin are you using? It will need to actually set the colours.

Please try https://github.com/nvim-tree/nvim-tree.lua which explicitly sets icon colours.

**Comment by Ethanol48** [comment]
I use that plugging, but my issue was resolved, I edited directly the source file, didn't find another way.
