### ISSUE TITLE
Display material icons in tabs dont work!

### ISSUE THREAD

**Issue by serhiihonchar1992** [nvim-tree/nvim-web-devicons#183]
Im use [LunarVim](https://github.com/lunarvim/lunarvim) config and [this File Explorer](https://github.com/DaikyXendo/nvim-tree.lua)
I did everything as in your documentation and this work, but it's icons doesn't work correctly for multiple tabs

**Take a look at screenshot 1**
<img src="https://i.ibb.co/9sJVDLs/2023-01-02-11-53-35.png">

**Take a look at screenshot 2**
<img src="https://i.ibb.co/yPbrFNZ/2023-01-02-11-56-47.png">

Please tell me how can I fix this?

**Comment by alex-courtis** [comment]
The icons are shown correctly in the tree but incorrectly on the tabs. This looks like a lunar vim issue. See [lunar vim example](https://github.com/LunarVim/LunarVim#showcase) with correct icons on the tabs.

Please raise a [lunarvim issue](https://github.com/LunarVim/LunarVim/issues/new/choose).

I note that you are using a fork of nvim-tree. The main repo is https://github.com/nvim-tree/nvim-tree.lua which is what lunar vim uses.

**Comment by alex-courtis** [comment]
Please reopen / comment if you have further issues.
