### ISSUE TITLE
Set all icons to one icon

### ISSUE THREAD

**Issue by kirill-martynov** [nvim-tree/nvim-web-devicons#189]
Hello!

I want to change all the file icons to one specific
Right now each filetype has it's own specific icon
<img width="154" alt="Screenshot 2023-01-22 at 02 07 02" src="https://user-images.githubusercontent.com/70448489/213891079-c966d983-5d50-4ad5-92e1-dbb6f81f007b.png">

I want to use only one icon for all the files
<img width="115" alt="Screenshot 2023-01-22 at 02 07 54" src="https://user-images.githubusercontent.com/70448489/213891193-583db275-e7d8-44ca-9084-823f9dce89ca.png">

How can I do this?

**Comment by alex-courtis** [comment]
This would depend on your context. You could for example:

`get_default_icon` or `get_icon_by_filetype('html')`

**Comment by kirill-martynov** [comment]
I've tried this: 
```
config.set_icon {
  lua = { icon = "" },
}
```

This worked only for lua, but is there a way to set icon for all files? 

I've also tried this: 
```config.set_default_icon("", "#6d8086")```

but it's not worked

**Comment by kirill-martynov** [comment]
I want this:
<img width="154" alt="Screenshot 2023-01-22 at 02 07 02" src="https://user-images.githubusercontent.com/70448489/213894345-7466a1a3-117e-4f0c-baa5-335bc931ff24.png">

Be like this:
<img width="155" alt="Screenshot 2023-01-22 at 02 43 13" src="https://user-images.githubusercontent.com/70448489/213894347-f259a098-5fa6-49dd-9e49-0b36ec46c747.png">

Use same icon

**Comment by alex-courtis** [comment]
I see: you want every file icon to be the same.

For the nvim-tree case it is simple: don't use web-devicons. It will then use `renderer.icons.glyphs.default` for all file icons.

You may have similar results for telescope.

**Comment by kirill-martynov** [comment]
@alex-courtis Thanks!

It's worked for nvim-tree
Now I need to find a same way to do this for telescope
