### ISSUE TITLE
transfer to nvim-lua

### ISSUE THREAD

**Issue by kyazdani42** [nvim-tree/nvim-web-devicons#19]
@tjdevries !

**Comment by tjdevries** [comment]
Do you still want to do this? Someone in chat just reminded me that I never did this :laughing:

**Comment by kyazdani42** [comment]
yep i'd still wish to, there are more and more people using this lib and i don't really have time to maintain / extend it by myself :)

**Comment by vuki656** [comment]
@tjdevries kind reminder. 

It would be a shame if this plugin didn't get more love since it's amazing.

**Comment by gegoune** [comment]
Alex is maintaining this plugin now. Given how old that issue is I will close it for now.
