### ISSUE TITLE
New icon for Makefile

### ISSUE THREAD

**Issue by kaboussi** [nvim-tree/nvim-web-devicons#198]

**Comment by alex-courtis** [comment]
Do you have an icon in mind?

**Comment by kaboussi** [comment]
> Do you have an icon in mind?

I think the gnu logo will be good.

**Comment by alex-courtis** [comment]
We actually do have an icon for `makefile` however that's not much use as it should be capitalised. https://github.com/nvim-tree/nvim-tree.lua/pull/1977#issuecomment-1420072224

We need to capitalise that.

**Comment by alex-courtis** [comment]
A PR would be gratefully appreciated.

**Comment by kaboussi** [comment]
Should we overwrite the 'makefile' with 'Makefile' or append it so we can have both?

**Comment by alex-courtis** [comment]
GNU make wants "GNUmakefile, makefile, and Makefile, in that order."

Let's have them all.

**Comment by alex-courtis** [comment]
It looks like nerd font has a makefile icon: https://www.nerdfonts.com/cheat-sheet

We should use that one, to be consistent.
