### ISSUE TITLE
Some icons don't show after changes in #199

### ISSUE THREAD

**Issue by Fedex159** [nvim-tree/nvim-web-devicons#205]
Some icons are not showing correctly, for example **rc.lua**. 

Here a video:

https://user-images.githubusercontent.com/44141208/219873564-decd124c-1aba-4ef9-8fc7-f4b66d56f795.mp4

---
Last commit where works: `d7f598ed63a66d6dce1117c61b0d5ba71b7c45e8`

**Comment by alex-courtis** [comment]
Thanks for reporting.

Reverting change.
