### ISSUE TITLE
Compound Extensions

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-web-devicons#206]
See #191, rolled back.

Only `test.js` highlights but not `foo.test.js`

/cc [nobuhikosawai](https://github.com/nobuhikosawai)

**Comment by gegoune** [comment]
How expensive/inefficient iterating over each `.` segment and comparing against available icons would be?

**Comment by alex-courtis** [comment]
> How expensive/inefficient iterating over each . segment and comparing against available icons would be?

That sounds the simplest. More efficient than string.find etc.

**Comment by nobuhikosawai** [comment]
I'll try to work on this again.
