### ISSUE TITLE
icon size

### ISSUE THREAD

**Issue by Andev70** [nvim-tree/nvim-web-devicons#219]
How to increase icons size

**Comment by gegoune** [comment]
It's up to your terminal and font to determine how glyphs get drawn, this plugin return icon codes only. Nothing we can do in term of icon sizes, etc.

**Comment by alex-courtis** [comment]
Some nerd fonts have different variations e.g. "Hack Nerd Font Mono" and "Hack Nerd Font" which have different sized glyphs.
