### ISSUE TITLE
get_icon function stops working when using custom telescope picker 

### ISSUE THREAD

**Issue by siduck** [nvim-tree/nvim-web-devicons#222]
Hi guys, did the get_icon function change in this [commit](https://github.com/nvim-tree/nvim-web-devicons/commit/b2060eac2fbc84e0637ea706378ff66451e7c424) ?

this require("nvim-web-devicons").get_icon("default_icon") doesnt work for me when I open my custom telecscope picker ( On this commit ) and i use that function in my custom tabline module too, if it fails then tabline crashes.

but it works fine in the previous commit

https://0x0.st/HzCF.mp4

**Comment by gegoune** [comment]
Could you please provide reproducible configuration and required steps?

**Comment by siduck** [comment]
nevermind i fixed it at my end
