### ISSUE TITLE
Small icons in neovim

### ISSUE THREAD

**Issue by lpuljic** [nvim-tree/nvim-web-devicons#224]
Hi, 

Sorry if this is a silly question, but I wanted to ask if its possible to fix the icon size or the quality of them.
<img width="54" alt="Screenshot 2023-03-09 at 10 34 14 am" src="https://user-images.githubusercontent.com/38928237/223877535-273777ad-25b9-41f2-b64a-0e2c4876e205.png">

As you can see in the image attached, the docker icon as well as the GO look just like a blue blob to be honest and not that clear at all.

I am using DroidSansMono Nerd Font

Thanks

**Comment by alex-courtis** [comment]
Closing as referenced discussion seems to cover it.

**Comment by lpuljic** [comment]
Hi @alex-courtis  not sure how the link covers my question, I am using iTerm2 its probably something I should have mentioned, or am I missing something?

**Comment by alex-courtis** [comment]
Do the icons appear the incorrect size when outside of vim?

You can test it out: `cat path/to/nvim-web-devicons/lua/nvim-web-devicons-light.lua`

**Comment by alex-courtis** [comment]
I'm afraid that appears to be an issue with your terminal, closing.

Does a mono variant of that font exist? In my case I use "Hack Nerd Font Mono" instead of "Hack Nerd Font "

**Comment by lpuljic** [comment]
Hi @alex-courtis 

No problems, thanks.

I have tried the ones that you use `Hack Nerd Font Mono`  and it's even worse, basically anything with MONO at the end icons look even smaller.

<img width="57" alt="Screenshot 2023-03-13 at 4 09 30 pm" src="https://user-images.githubusercontent.com/38928237/224613045-4002a5ab-7878-428b-b4cf-cea1818dae24.png">

might ask in iTerm2
