### ISSUE TITLE
Different icon sizes shown by nvim-tree and Diffview

### ISSUE THREAD

**Issue by gegoune** [nvim-tree/nvim-web-devicons#225]
Hey, trying to get my head around an issue I just observed, seems like two plugins using nvim-web-devicons show icons differently:

<img width="615" alt="sizes" src="https://user-images.githubusercontent.com/69750637/224421097-98306a43-1a0d-444d-a6da-9b048cf1a28c.png">

On the left is nvim-tree, on the right Diffview. Terminal emulator is Wezterm and when I copy both of those glyphs with mouse and try to get their codes both return the same:

```
 0     \u{e620}     x_adv=10 cells=1  glyph=i_seti_lua,495  wezterm.font("Symbols Nerd Font Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
```

Once copied by mouse and pasted to other window they show as bigger size (right on screenshot). Any ideas where this difference might be coming from?

(related https://github.com/nvim-tree/nvim-web-devicons/issues/224?)

**Comment by T-727** [comment]
Wezterm by default allows glyphs to overflow when the next character is a space

**Comment by gegoune** [comment]
That's it. Feeling bit silly now, thank you for pointers!
