### ISSUE TITLE
Run nerdfix to replace deprecated nerdfont icons

### ISSUE THREAD

**Issue by mrjones2014** [nvim-tree/nvim-web-devicons#242]
https://github.com/loichyan/nerdfix

This tool will ensure you are using the up to date icons that are in the private use unicode range.

**Comment by gegoune** [comment]
Related to https://github.com/nvim-tree/nvim-web-devicons/issues/192?

**Comment by mrjones2014** [comment]
Yeah, it looks like that is related. We can close this and just mention the nerdfix tool as an option on the other issue.
