### ISSUE TITLE
Just try an astro project. But there is no icon for it!

### ISSUE THREAD

**Issue by Nitesh000** [nvim-tree/nvim-web-devicons#245]
Really appreciate your work guys, been using your product for months. Hope you guys add this icon too.

**Comment by siduck** [comment]
duplicate of https://github.com/nvim-tree/nvim-web-devicons/issues/300

raise a request at nerdfonts repo for adding astro icon, as nvim-tree uses that

**Comment by gegoune** [comment]
As @siduck said, duplicate of #300.
