### ISSUE TITLE
svelte / html icon wrong

### ISSUE THREAD

**Issue by halafi** [nvim-tree/nvim-web-devicons#257]
<img width="227" alt="icons" src="https://user-images.githubusercontent.com/5550440/231959622-904b94c9-ac9d-4909-b271-48d730d9019a.png">

I think this used to work, I also didn't change font (using FIraCode), the filetype is detected correctly but html has svelte icon and svelte has ?

**Comment by gegoune** [comment]
<img width="133" alt="svelte" src="https://user-images.githubusercontent.com/69750637/231988107-3b76e918-d586-4b44-b26b-e4993c7c216c.png">
Seems like issue with your font.

**Comment by halafi** [comment]
I tried to reinstall patched font, but it doesn't make much sense if the svelte icon is displayed for .html files, does it?

**Comment by gegoune** [comment]
I don't think it's svelte icon. Looks like html icon to me (on mobile).
