### ISSUE TITLE
Icons missing after updating Nerdfonts to v3.0.0

### ISSUE THREAD

**Issue by LnLcFlx** [nvim-tree/nvim-web-devicons#265]
Many icons are not displayed correctly.
This is likely due to a restructuring of the Material Design icons in the new Nerdfont release 3.0.0 as described [here](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0).

**Comment by Flygrounder** [comment]
You might be interested in discussion in #264

**Comment by bitzcoder** [comment]
Same problem. Had to manually fix every single file containing the broken icons with [Nerdfix](https://github.com/loichyan/nerdfix)
