### ISSUE TITLE
nvim-web-devicons make other plugins bugged with floating texts

### ISSUE THREAD

**Issue by hilmiwicak** [nvim-tree/nvim-web-devicons#271]
## Image / video that shows the bug

Here below is telescope with nvim-web-devicons
![telescope with nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons/assets/73383379/88f71617-9989-40d0-9ede-f232ff21ca10)

Below is telescope without nvim-web-devicons
![telescope without nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons/assets/73383379/ed4765db-5f6e-42e7-a71e-c1f91fdc52a3)

## Steps to reproduce

1. Copy `init.lua` below

<details>
    <summary>Click to expand init.lua</summary>

    local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
    if not vim.loop.fs_stat(lazypath) then
      vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
      })
    end
    vim.opt.rtp:prepend(lazypath)
    
    require("lazy").setup({
      { "nvim-lua/plenary.nvim", },
      {
        "nvim-telescope/telescope.nvim",
        dependencies = {
          "nvim-lua/plenary.nvim",
        },
        config = function ()
          local telescope_action_layout = require("telescope.actions.layout")
    
          require("telescope").setup({
            defaults = {
              initial_mode = "insert",
              mappings = {
                n = {
                  ["<M-/>"] = telescope_action_layout.toggle_preview,
                },
                i = {
                  ["<M-/>"] = telescope_action_layout.toggle_preview,
                }
              },
              preview = {
                hide_on_startup = true,
                filesize_limit = 10,
                treesitter = true,
              }
            },
            fzf = {
              fuzzy = true,
              override_generic_sorter = true,
              override_file_sorter = true,
              case_mode = "smart_case",
            },
          })
        end,
      },
    
      {
        "kyazdani42/nvim-web-devicons",
        config = function()
          require("nvim-web-devicons").setup({
            default = true,
          })
        end,
      },
    })

</details>

2. `nvim -u ~/nvim-test-config/init.lua`
3. let lazy install the plugins
4. `:Telescope find_files` and see that there are some floating texts
5. Comment `nvim-web-devicons` part of lazy setup
6. Close nvim
7. `nvim -u ~/nvim-test-config/init.lua`
8. `:Telescope find_files` and there are no floating texts anymore

**Comment by scardenasb** [comment]
It seems to be because some icons code, it was happening to me with ".txt" icon, so I replaced it with the same icon but the version for mi os (unix), using: `require("nvim-web-devicons").setup({
	override_by_extension = {
		["txt"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Txt",
		},
	},
})
`

**Comment by hilmiwicak** [comment]
Thank you for your reply @scardenasb ! I think this bug exist because tmux rendered it wrong. I just tried it outside tmux and it works just fine.

**Comment by nullwiz** [comment]
> Thank you for your reply @scardenasb ! I think this bug exist because tmux rendered it wrong. I just tried it outside tmux and it works just fine.

Can confirm, I was having a similar issue in nvim-tree, where characters just end up there.  Without tmux, it works fine.

**Comment by alex-courtis** [comment]
Great news!

**Comment by BartSte** [comment]
> Thank you for your reply @scardenasb ! I think this bug exist because tmux rendered it wrong. I just tried it outside tmux and it works just fine.

Did you find a solution to make tmux render them correctly? Or did you just stop using tmux?

**Comment by scardenasb** [comment]
> > Thank you for your reply @scardenasb ! I think this bug exist because tmux rendered it wrong. I just tried it outside tmux and it works just fine.
> 
> Did you find a solution to make tmux render them correctly? Or did you just stop using tmux?

I just left those 'override_by_extension' in my file and keep using Tmux, but as people said, it must be because of my Tmux terminal settings; it just doesn't work fine with my terminal and Nvim configurations. I haven't tried to solve it honestly; 'override_by_extension' does not bother me yet xd

**Comment by alex-courtis** [comment]
Check your terminal then `$TERM`

The terminal you started tmux from must be able to render the icons. Check `$TERM` and test from outside of tmux.

Test again from within tmux: what is the `$TERM` ?

**Comment by BartSte** [comment]
@alex-courtis, thanks for your help.

I encounter the issue when running: Alacritty on windows + WSL2 + tmux
As expected, the issue does not exist when I run Alacritty on windows + WSL2 (without tmux).

My `$TERM` without tmux is: `xterm-256color`.
My `$TERM` with tmux is: `tmux-256color`.

When setting up tmux, I followed neovim's [recommendations](https://neovim.io/doc/user/term.html).

After doing some digging, I found a [closed issue](https://github.com/tmux/tmux/issues/3566#issuecomment-1551236008) on the tmux repo suggesting the rendering issue was due to an issue with Window's ConPTY.

Also, this [reddit post](https://www.reddit.com/r/neovim/comments/13hz4qj/floating_text_bug_in_telescope/) exactly matches the issue I had. No one suggested a solution, unfortunately. 

Since only a small subset of the icons render incorrectly, the easiest workaround is to just replace those with other icons in my config.

I guess this is not an issue that can be solved by this repo, but hopefully these posts can help others encountering the same issue.

**Comment by alex-courtis** [comment]
Nice digging! Could I please ask you to post some of those icons? It will be a useful reference for others that will likely experience the same issue.

**Comment by BartSte** [comment]
Here a video of the issue:
- https://github.com/nvim-tree/nvim-web-devicons/assets/62509788/2ca09aaa-531e-4b16-b976-19bb06362c75

I encountered the issue with the icons related to the following file extensions:
- txt
- svg
- xml
- xmll
- xll
- scm
- smm
- toml
- docx
- log

**Comment by BartSte** [comment]
Oke I found the issue. I is indeed an issue with window's conpty. So for anyone encountering this issue, you need to make sure you have the latests version of conpty.dll and OpenConsole.exe, as is described in this [post](https://github.com/alacritty/alacritty/issues/7792).

**Comment by alex-courtis** [comment]
Great news.

I'm not quite understanding the issue; can I please ask you to draft a section for README.md?

A PR would be great.

```md
You can also use `get_icon_name_by_filetype(filetype)` to get the icon name associated with the filetype.

## Known Issues

### XXX not rendering in Alacritty on windows

Ensure something something dll...

## Contributing

PRs are always welcome! Please see [CONTRIBUTING](CONTRIBUTING.md)
```
