### ISSUE TITLE
PS1 icons not visible in neovim

### ISSUE THREAD

**Issue by harshv1741** [nvim-tree/nvim-web-devicons#272]
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/51878195/d9639ff8-b47b-4a3b-addb-c83f61ec0da2)

Hello, as you can see in the screenshot, the ps1 PowerShell script icons are not showing. I'm using CascaydiaCove nerd font. I don't know the reason why it stopped working, could anyone help me regarding this matter

**Comment by gegoune** [comment]
Most likely you will need to update to latest version of your font as there were changes to need fonts recently.
