### ISSUE TITLE
Icons width is wrong for some icons

### ISSUE THREAD

**Issue by nullwiz** [nvim-tree/nvim-web-devicons#275]
I am having an issue where the width of some icons is wrong, for example, folders. 
I am using CaskaydiaCove Nerd Font Monospaced, but I also tried with other fonts with no luck. 
See the following example:
 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/1305731/be0ba362-e4f4-464a-9fdf-f196e68de931)

Steps to reproduce:

- Clone my dotfiles:
 https://github.com/nullwiz/dotfiles/tree/main/nvim/nvim
-  Run :so and :PackerSync in lua/nullwiz/packer 
-  space + pv opens up nvim-tree

**Comment by alex-courtis** [comment]
I've seen that. I use hack.

For monospaced icons I need to use "Hack Nerd Font Mono" rather than "Hack Nerd Font".

See if you can find another variant of your font or try another font.

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    ....
    <alias>
        <family>monospace</family>
        <prefer>
            <family>Hack Nerd Font Mono</family>
        </prefer>
    </alias>
    ....
</fontconfig>
```

**Comment by nullwiz** [comment]
Fixed.

For anyone having a similar issue, what I did is to delete all profiles. 
For some reason, the windows terminal was not changing the font. 

Solved it by deleting all profiles, creating a new one, and the font was properly changed.
