### ISSUE TITLE
Add custom icons for .cu ( cuda) files

### ISSUE THREAD

**Issue by basava70** [nvim-tree/nvim-web-devicons#296]
Hi,
Thanks for the awesome plugin.
I wanted to ask if there is  a way to add custom icons for new  file types not listed in the plugin.
One way, I found is to add it to "lua/nvim-web-devicons.lua". But that would break any future updates.
I was wondering if there is another intended way to add icons for new file types.
Thanks in advance.

**Comment by gegoune** [comment]
If that's widely recognised filetype and there is no already existing icon for the same extension we can add it here. PR welcome. :)

**Comment by basava70** [comment]
I don't think cuda is as heavily used as python or cpp. It's only used for parallel programming. As of now, I don't even see an existing file type. Which is why I thought it would probably cool to add a random Nvidia icon myself via this plugin if possible.

**Comment by alex-courtis** [comment]
> Which is why I thought it would probably cool to add a random Nvidia icon myself via this plugin if possible.

No thank you. Let's keep company logos out of this; there can be copyright an other legal issues when used without their permission.

**Comment by basava70** [comment]
Can you at least make it possible to add custom icons for new file types as part of customizing nvim-web-devicons ?

**Comment by alex-courtis** [comment]
> Can you at least make it possible to add custom icons for new file types as part of customizing nvim-web-devicons ?

Of course, please see https://github.com/nvim-tree/nvim-web-devicons#set-an-icon

**Comment by basava70** [comment]
Thanks for the reply. Probably a little late. But that set_icon only works to override an existing filetype is it not ?. I tried changing it for .cu files but i stll get the default icon for .cu filetype. Is there anything else I can try ?

**Comment by gegoune** [comment]
It would help if you showed the code you written that doesn't work.

**Comment by basava70** [comment]
Nvm I made a minor mistake. It is working now. Thanks a ton :)
