### ISSUE TITLE
Make `refresh*` functions public

### ISSUE THREAD

**Issue by simonmandlik** [nvim-tree/nvim-web-devicons#298]
It would be great to be able to call `require("nvim-web-devicons").refresh*` functions programatically on demand, not only on autocommand. This would help immensely especially during startup, when autocommands may not (yet) be available.

If you agree, I can make a PR for that

**Comment by alex-courtis** [comment]
That sounds reasonable. We should call `set_up_highlights` as well.

Yes please, do create a PR: https://github.com/nvim-tree/nvim-web-devicons/blob/master/CONTRIBUTING.md

**Comment by simonmandlik** [comment]
Sure, here it is https://github.com/nvim-tree/nvim-web-devicons/pull/301
