### ISSUE TITLE
add icon astro

### ISSUE THREAD

**Issue by henryy-el** [nvim-tree/nvim-web-devicons#300]

**Comment by gegoune** [comment]
PR welcome.

**Comment by alex-courtis** [comment]
nvim-web-devicons can only work with the icons provided by your terminal's font, specifically https://www.nerdfonts.com/

A quick look didn't reveal an icon, it looks like you'll need to source one and request to add it.

**Comment by BrunoKrugel** [comment]
Already requested at nerdfonts https://github.com/ryanoasis/nerd-fonts/issues/1172

**Comment by pauchiner** [comment]
We all know that until nerd fonts implements a glyph for astro, a PR cannot be made, but temporarily a solution can be given with the rocket glyph already available:

<img width="128" alt="Captura de pantalla 2024-01-11 a las 10 49 02" src="https://github.com/nvim-tree/nvim-web-devicons/assets/49660697/8611d5aa-038c-45ac-86ed-7cbb165415d5">

I already implemented this in my nvim configuration and looks like this:

<img width="256" style="border-radius: 15px;" alt="Captura de pantalla 2024-01-11 a las 10 50 20" src="https://github.com/nvim-tree/nvim-web-devicons/assets/49660697/2a7dd5c1-cf15-425c-91d4-96a1f2877b02">

**Comment by akring** [comment]
Great solution, and let me make it more clearly:
```
  opts = {
    strict = true,
    override_by_extension = {
      ["astro"] = {
        icon = "",
        color = "#f1502f",
        name = "Astro",
      },
    },
  },

```

**Comment by AlejandroSuero** [comment]
I am using this one as my icon.

<img width="160" alt="Nerd Font ArcoLinux icon" src="https://github.com/nvim-tree/nvim-web-devicons/assets/71392160/a8db64f6-b0b3-42ea-890f-3d2384994bbb">

This is how it looks implemented.

<img width="519" alt="Astro icon in use" src="https://github.com/nvim-tree/nvim-web-devicons/assets/71392160/fbc3e33f-f405-4028-be35-5586919a669d">

```lua
astro = {
 icon = "",
 color = "#ffffff",
 name = "Astro",
}
```
