### ISSUE TITLE
Git Staged symbol missing

### ISSUE THREAD

**Issue by jelleh** [nvim-tree/nvim-web-devicons#305]
### Description

Following glyphs are not matching nerd font 3.0.2-2 ?

I think it is related to this issue: https://github.com/ryanoasis/nerd-fonts/issues/1190

```
local DEFAULT_OPTS = {
  renderer = {
    icons = {
      glyphs = {
        git = {
          unstaged = "✗",
          staged = "✓",
          untracked = "★",
        },
      },
    },
  },
}

```

### Neovim version

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958
```

### Operating system and version

Linux 6.5.3-arch1-1

### nvim-tree version

a3aa3b4

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua
2. :NvimTreeToggle
3. Browse to git repo with staged or unstaged files

### Expected behavior

Should get git status icons before files

### Actual behavior

Icons not displayed, just []

**Comment by jelleh** [comment]
I have 3.0.2-1 installed, 3.0.2-2 was thet versions of nerd font symbols
I have tried hack and bitstream, same problem.

pacman -Q |grep nerd
ttf-bitstream-vera-mono-nerd 3.0.2-1
ttf-hack-nerd 3.0.2-1
ttf-nerd-fonts-symbols 3.0.2-2
ttf-nerd-fonts-symbols-common 3.0.2-2
ttf-nerd-fonts-symbols-mono 3.0.2-2

**Comment by alex-courtis** [comment]
I've never actually used `ttf-nerd-fonts-symbols`, just `ttf-hack-nerd` with alacritty

`fontconfig/fonts.conf`
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    ...
    <alias>
        <family>monospace</family>
        <prefer>
            <family>Hack Nerd Font Mono</family>
        </prefer>
    </alias>
    ...
</fontconfig>
```

Alacritty is using the default monospace
```yaml
# Font configuration
#font:
  # Normal (roman) font face
  #normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    #family: monospace

    # The `style` can be specified to pick a specific face.
    #style: Regular
```

I did try installing the symbols however didn't see any change. I don't think I am replicating this correctly.
```
:; pacman -Q |grep nerd
containerd 1.7.6-1
ttf-hack-nerd 3.0.2-1
ttf-nerd-fonts-symbols 3.0.2-2
ttf-nerd-fonts-symbols-common 3.0.2-2
ttf-nerd-fonts-symbols-mono 3.0.2-2
```

Both alacritty and xterm functioned as expected.

Please share you terminal/font config so that we can investigate.

**Comment by jelleh** [comment]
Hi i am using kitty and have installed this fonts:
% pacman -Q |grep nerd
ttf-bitstream-vera-mono-nerd 3.0.2-1
ttf-hack-nerd 3.0.2-1
ttf-nerd-fonts-symbols 3.0.2-2
ttf-nerd-fonts-symbols-common 3.0.2-2
ttf-nerd-fonts-symbols-mono 3.0.2-2


This is the font config part of kitty, everything else font related is default.

##font_family      BitstromWera Nerd Font Mono
##bold_font        BitstromWera Nerd Font Mono Bold
##italic_font      BitstromWera Nerd Font Mono Oblique
##bold_italic_font BitstromWera Nerd Font Mono Bold Oblique

font_family      Hack Nerd Font Mono
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Oblique
bold_italic_font Hack Nerd Font Mono Bold Oblique


Normally i use Bitstrom, but with above config same behaviour.

**Comment by alex-courtis** [comment]
Installed kitty and set:
```
font_size 15.0
font_family Hack Nerd Font Mono
bold_font Hack Nerd Font Mono Bold
italic_font Hack Nerd Font Mono Oblique
bold_italic_font Hack Nerd Font Mono Bold Oblique
```

Git symbols display as expected.

Sorry mate, I can't help you here. I suggest you contact kitty. It might be useful to share your `~/.config/fontconfig/fonts.conf` if you raise an issue with them.
