### ISSUE TITLE
File with .md extension show unknown icon

### ISSUE THREAD

**Issue by jonahfang** [nvim-tree/nvim-web-devicons#306]
I use iTerm2 (v3.5.0beta11) with macOS Monterey, and installed v3.0.2 Hack Nerd Font.
I searched the website <https://www.nerdfonts.com/cheat-sheet>, found that:

```
  nf-dev-markdown (\ue73e) <--- Display OK
  nf-oct-markdown (\uf48a) <--- Unknown icon is this 
```

<img width="336" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/16301509/5758b966-abb9-4b55-b539-822453c692dc">

**Comment by alex-courtis** [comment]
What are you using to show icons? nvim-tree?

It's up to the plugin do decide which symbol to display.

**Comment by jonahfang** [comment]
This problem maybe come from iTerm2.

**Comment by alex-courtis** [comment]
You can try testing the terminal directly:

![20230923_140235](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/ea9ed12d-97c7-48e0-ad98-e715a4f13608)

**Comment by jonahfang** [comment]
I have tested it:
<img width="1017" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/16301509/6d8d41d3-96a6-49e2-953e-9ca0392cf458">

**Comment by alex-courtis** [comment]
Sorry mate, it's your terminal.

**Comment by jonahfang** [comment]
Can I config this plugin to change the icon of md?

**Comment by alex-courtis** [comment]
Yes. You can make many changes: https://github.com/nvim-tree/nvim-web-devicons#set-an-icon

**Comment by jonahfang** [comment]
@alex-courtis it works, thanks!
