### ISSUE TITLE
TOML icon broken

### ISSUE THREAD

**Issue by kiyoon** [nvim-tree/nvim-web-devicons#360]
It seems like the icon for toml filetype is broken, or at least wezterm can't render the icon.

**Comment by alex-courtis** [comment]
alacritty with HackNerdFontMono-Regular.ttf can render it. What does this look like for you?

![20231226_091447](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/de20055a-9405-4fdb-ba71-ca7a4d8cdc43)

**Comment by kiyoon** [comment]
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/12980409/6486827a-3678-4dce-9868-43c2c18a4bd1)

The box next to the `pyproject.toml` is what I see, plus the warning from wezterm that it couldn't render.

**Comment by yusufshalaby** [comment]
Same issue here. Ue6b2 is not in Symbols Nerd Font

**Comment by n-crespo** [comment]
> You probably need to update your Nerd font, I did this and it fixed it. This repo switched to the updated TOML icon recently

@ribru17 What font did you use that worked for you? I tried re-installing JetBrains Mono NF but it doesn't seem to have worked properly.

**Comment by yusufshalaby** [comment]
> > You probably need to update your Nerd font, I did this and it fixed it. This repo switched to the updated TOML icon recently
> 
> @ribru17 What font did you use that worked for you? I tried re-installing JetBrains Mono NF but it doesn't seem to have worked properly.

You might need to explicitly map the new toml code (U+E6B2) to the nerd font. I have this in my kitty config:
`symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0,U+E6B2 Symbols Nerd Font Mono`

**Comment by kiyoon** [comment]
OK, updating the nerd font (JetBrains Mono NF) fixed the issue. Thank you!

**Comment by wookayin** [comment]
TOML Unicode: 

I also confirm that JetBrainsMono Nerd Font v3.1.1 fixed the TOML icon. It was broken in v3.1.0.
