### ISSUE TITLE
Are you open to a PR for adding operating system icons?

### ISSUE THREAD

**Issue by miversen33** [nvim-tree/nvim-web-devicons#361]
I know that devicons is traditionally used for showing the icons of files, but I am looking for an easy way to show the icons of an operating system.

Per [this comment on #155](https://github.com/nvim-tree/nvim-web-devicons/issues/300#issuecomment-1704038616), nvim-web-devicons can use icons provided by nerdfonts.

Nerdfonts provides several icons for popular operating systems and linux distros

It would be pretty slick if we could include these icons as well.

If the team is open to it, I would happily contribute this

**Comment by alex-courtis** [comment]
Yes please [Contributions are always welcome](https://github.com/nvim-tree/nvim-web-devicons/blob/master/CONTRIBUTING.md)

I imagine we would have to use the distro name as the extension and name. Users could request the icon by distro.

**Comment by hasecilu** [comment]
Maybe this should be closed as #433 included all the icons of OSs from Nerd Fonts - Font Logos.

**Comment by alex-courtis** [comment]
> Maybe this should be closed as #433 included all the icons of OSs from Nerd Fonts - Font Logos.

Thank you.

You should have permissions to close issues etc.

Please let me know if you can't close this one!

**Comment by hasecilu** [comment]
Yes I can, I just wanted to discuss first, but yeah, for this issue the result is pretty straight forward.

**Comment by alex-courtis** [comment]
> Yes I can, I just wanted to discuss first, but yeah, for this issue the result is pretty straight forward.

Excellent. You have my trust.
