### ISSUE TITLE
Package-lock.json file name causes error

### ISSUE THREAD

**Issue by sethen** [nvim-tree/nvim-web-devicons#363]
Using something like this in overrides causes an error in Neovim

```lua
["package-lock.json"] = {
   icon = "",
   name = "Package-lock.json"
}
```

I get this whenever I open an directory with a `package-lock.json` file in it in nvim-tree.  Funny enough the icon works though.

![Untitled](https://github.com/nvim-tree/nvim-web-devicons/assets/1493530/01ed7927-ef26-4d76-99b0-6f193a980071)

**Comment by Akmadan23** [comment]
The `-` character is not allowed in group names, having that in the `name` field causes the error.

**Comment by sethen** [comment]
Is there anyway for me to change the icon of this file then by targeting that file name?

**Comment by Akmadan23** [comment]
There's nothing wrong with the file name itself (the `["package-lock.json"] = ` part), the issue is with the `name` field, which only affects the highlight group, so it can be different (by default it's "PackageLockJson").
