### ISSUE TITLE
New JS icon is not legible/recognizable in small size

### ISSUE THREAD

**Issue by MunifTanjim** [nvim-tree/nvim-web-devicons#373]
- https://github.com/nvim-tree/nvim-web-devicons/pull/366

This is the new JS Icon:

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/8a7f4bab-9ca9-4a90-926d-f85a57832f72)

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/adc054b3-8b0a-4029-904d-5111917f3d8c)

In small size, it's not legible/recognizable at all:

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/c0284927-78f7-4b0e-84d5-958a29390fcc)

The previous one was much better:

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/f75391a6-3f6a-4b08-ba56-ce8f4ecfff3f)

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/1501b15f-830c-4613-a692-68f033816043)

Same for CJS and MJS:

- https://github.com/nvim-tree/nvim-web-devicons/pull/368

**Comment by MunifTanjim** [comment]
I think we should revert those 2 PRs.

cc: @alex-courtis @ronitkrshah

**Comment by ronitkrshah** [comment]
@MunifTanjim Well it's looking fine for me in Termux also in my PC

![Screenshot_20240103-192939](https://github.com/nvim-tree/nvim-web-devicons/assets/118371892/605a3044-d2a3-470c-b6e1-eef435c3dc1c)
![Screenshot_20240103-192931_Termux](https://github.com/nvim-tree/nvim-web-devicons/assets/118371892/cb99f62d-19f1-4220-9c58-07adf9348159)

**Comment by MunifTanjim** [comment]
I guess it's terminal dependant.

Alacritty:
<img width="27" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/8ca7700b-be22-4013-813d-3fc6433b0ef2">

Kitty:
<img width="27" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/664717b6-0c61-45a0-a508-9b65b6c1073d">

WezTerm: 
<img width="27" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/8050659/ff9d3eee-2aa7-4314-9e9a-046d88310bf7">

**Comment by ronitkrshah** [comment]
It depends on the `font size` of your terminal. Naturally, if you are using a smaller font size, it will show a small icon, and vice versa for a bigger font size.

**Comment by MunifTanjim** [comment]
Also depends on how the terminal renders the font.

In either way, the new icon is not very recognizable in small size. The previous one was immediately recognizable.

**Comment by ronitkrshah** [comment]
Hmm ....Then we should revert this 2 PRs

**Comment by gegoune** [comment]
I am leaning toward using 'official' icons as much as possible, mainly in order to avoid discussions which icon fits user's preferences best. @MunifTanjim obviously I am not having a go or disrespecting you and your concern here, it's just that this icon is what it is. Just my opinion.

**Comment by MunifTanjim** [comment]
Makes sense. No worries.

**Comment by gegoune** [comment]
Let's hear @alex-courtis' and @Akmadan23 opinions on this as well.

**Comment by alex-courtis** [comment]
Let's stick to the official icons.

If the official icon is not usable, it's something that should and very likely will be fixed in the font itself.

**Comment by alex-courtis** [comment]
Closing off; we can revisit and raise upstream if it continues to be a problem.
