### ISSUE TITLE
Icons for C++20 module files doent work

### ISSUE THREAD

**Issue by neg-c** [nvim-tree/nvim-web-devicons#390]
C++20 introduced modules and different compilers have different file extensions:
MSVC: .ixx
Clang: .cppm .cxxm .ccm
GCC: .mpp

It would be nice to at least recognize files with these extensions as C++ files and add appropriate icons

**Comment by gegoune** [comment]
This repository relies on contributions from users. PR adding those extensions will be welcomed.
