### ISSUE TITLE
Highlight Error

### ISSUE THREAD

**Issue by smsjr** [nvim-tree/nvim-web-devicons#398]
Since the commit 55e956f, I'm getting this error message:

Error detected while processing /home/smsjr/.config/nvim/init.lua:
E5248: Invalid character in group name
E5113: Error while calling lua chunk: ...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:262: Invalid highlight name: 'DevIconZig Object Notation'
stack traceback:
[C]: in function 'nvim_set_hl'
...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:262: in function 'set_up_highlight'
...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:290: in function 'set_up_highlights'
...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:363: in function 'setup'
...r/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:803: in function 'setup'
/home/smsjr/.config/nvim/lua/plugins/config/nvim-tree.lua:44: in main chunk
[C]: in function 'require'
/home/smsjr/.config/nvim/lua/plugins/init.lua:39: in main chunk
[C]: in function 'require'
/home/smsjr/.config/nvim/init.lua:30: in main chunk

**Comment by mfurquimdev** [comment]
Thank you for pointing out the breaking commit.
For those using NVchad and I have fixed this issue by pinning to the previous commit.

On `lua/custom/plugins.lua`
```
local plugins = {
    {
        "nvim-tree/nvim-web-devicons",
        commit = "313d9e7193354c5de7cdb1724f9e2d3f442780b0",
    },
}
```

**Comment by smsjr** [comment]
There's already a pull request fixing the problem. Waiting for merge. Thx!

**Comment by s1nistr4** [comment]
Found a temporary fix

1. Run :Lazy 
2. Remove the nvim-web-devicons package 
3. Replace the line in your plugins config with this:

`
        {
            "kyazdani42/nvim-web-devicons", -- make icons work
            commit = "7eecd529a6e861c81a80624db16e9b74c50a49eb"
        },
`

5. Run :Lazy install

**Comment by smsjr** [comment]
@s1nistr4, the bug has already fixed in the last commit. You can now install the plugin without specify the previous commit.

**Comment by smsjr** [comment]
@s1nistr4, the bug has already fixed in the last update. You can now install the plugin without specify the previous commit.
