### ISSUE TITLE
Haxe icon not showing

### ISSUE THREAD

**Issue by bwkam** [nvim-tree/nvim-web-devicons#402]
It's the only icon I can't see besides .hx files, I'm using latest nvim-web-devicons and even overridden it to make sure:
```lua
require("nvim-web-devicons").setup({
	strict = true,

	override_by_extensions = {
		hx = {
			icon = "",
			color = "#EA8220",
			name = "haxe",
		},
	},
})
```
I'm the one who [added it](https://github.com/nvim-tree/nvim-web-devicons/pull/394), although it wasn't working for me at that time. Would appreciate if someone helped or tested whether it really works. It just shows the default icon
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/91009118/e1dc68ce-3272-4b1e-982b-9681e8e96a84)

**Comment by alex-courtis** [comment]
Looking good on nvim-tree / nvim-web-devicons master:

![20240217_132300](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/8f620d0c-4945-4bec-ad4a-b7a892ad94af)

You could try a ["Clean Room" Replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) to see if it's something in your vim setup.

**Comment by bwkam** [comment]
Thanks, it was a problem indeed with my config.
