### ISSUE TITLE
Add mp3 file icons

### ISSUE THREAD

**Issue by pauchiner** [nvim-tree/nvim-web-devicons#404]
### Current Behaviour

<img width="311" alt="Captura de pantalla 2024-02-22 a las 14 24 09" src="https://github.com/nvim-tree/nvim-web-devicons/assets/49660697/b6982484-6d8c-4e33-a02b-a33287815d8f">

I think that any of these icons would be a great fit in this case:

<img width="1096" alt="Captura de pantalla 2024-02-22 a las 14 24 46" src="https://github.com/nvim-tree/nvim-web-devicons/assets/49660697/48657300-7ad3-4535-aed7-f346c521f1cc">

**Comment by alex-courtis** [comment]
Unfortunately no seti icon other than nf-seti-audio which isn't the greatest fit.

![20240224_134233](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/cc2f88fb-c937-4dc2-b69c-590bb13911e5)

**Comment by alex-courtis** [comment]
Apologies for the miscommunication @pauchiner ; I simply meant that there was nothing available from seti for us to use.

Please do raise a PR with one of the icons you proposed.

If you're keen we could add it for some more file types but that's up to you.

**Comment by pauchiner** [comment]
I created the PR with only the mp3 file icons. I also add more audio files extensions that uses those icons?

**Comment by alex-courtis** [comment]
> I created the PR with only the mp3 file icons. I also add more audio files extensions that uses those icons?

That would be fantastic, yes please.

If specific icons are created in the future we can easily change to them.
