### ISSUE TITLE
Regression: `NvimWebDeviconsHiTest` crashes

### ISSUE THREAD

**Issue by simeonoff** [nvim-tree/nvim-web-devicons#419]
I believe after merging [this PR](https://github.com/nvim-tree/nvim-web-devicons/pull/417) the panel now crashes with:

<img width="1133" alt="Screenshot 2024-03-18 at 08 36 45" src="https://github.com/nvim-tree/nvim-web-devicons/assets/4118303/2362acdd-c22b-4248-8261-ac8cba6a7fcf">

I have the `font-symbols-only-nerd-font` cask installed via `brew`(macOS) which is at version 3.1.1 of the nerd font symbols and they don't include the prettier icon.

**Comment by simeonoff** [comment]
My bad, it was down to the way I have overwritten the config for some icons. 🫣

**Comment by alex-courtis** [comment]
This should be hardened / fixed. The failed icon can be shown as an error.

**Comment by alex-courtis** [comment]
Fix incoming: #423

@simeonoff I'd be most grateful if you could test this one with your original case:

```sh
cd /path/to/nvim-web-devicons
git pull
git checkout 419-hi-test-fail-on-bad-icon
```

When you're finished testing:
```sh
git checkout master
```

**Comment by simeonoff** [comment]
> @simeonoff I'd be most grateful if you could test this one with your original case:

Will do!

**Comment by simeonoff** [comment]
Ok, tested it, works like a charm! No more errors being thrown.
