### ISSUE TITLE
Missing icon for Java

### ISSUE THREAD

**Issue by Maduki-tech** [nvim-tree/nvim-web-devicons#420]
Hello,

i realised that there is a Java icon missing, 

this is the response I get, when I run 
```
:lua require"nvim-web_devicons".get_icons()
```

![Screenshot 2024-03-18 at 17 16 36](https://github.com/nvim-tree/nvim-web-devicons/assets/70664223/fec0879d-c89f-419d-aabd-9a8e0a690573)

**Comment by alex-courtis** [comment]
Was it an issue with the terminal font?

**Comment by Maduki-tech** [comment]
Yes, somehow my font did not support the Java Icon but everything else was supported.
