### ISSUE TITLE
Incorrect NF symbol shown for Rust

### ISSUE THREAD

**Issue by chardon55** [nvim-tree/nvim-web-devicons#427]
I think there is something not matched to nerd fonts.

Bold fonts are fine. This issue only comes with regular fonts.

<img width="79" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/44740171/71877ccf-4471-405c-8667-33db146d9c8e">

---

Nerd fonts version: 3.1.1 (Fira Code patch)
nvim-web-devicons branch: master
Neovim version: 0.9.5

**Comment by chardon55** [comment]
Okay it also happens outside neovim. I think it's nerd fonts' issue.

**Comment by baco** [comment]
It seems the icon being used is `ue68b` instead of `ue7a8`. Both have the same glyph according to NF site:

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/102958/bccb8a19-2abd-4aa5-ba32-a4a3d6392859)

but when downloading the assets, if we only download the Monospaced version, the `.ttf` file only has `ue7a8` glyph available.

**Comment by chardoncs** [comment]
> It seems the icon being used is `ue68b` instead of `ue7a8`. Both have the same glyph according to NF site:
> 
> ![image](https://github.com/nvim-tree/nvim-web-devicons/assets/102958/bccb8a19-2abd-4aa5-ba32-a4a3d6392859)
> 
> but when downloading the assets, if we only download the Monospaced version, the `.ttf` file only has `ue7a8` glyph available.

I solved the issue by removing some fonts. That should be a conflict with other font files.

**Comment by baco** [comment]
@chardoncs what can I say, I can not ditch the other one; It's system-wide installed:
```
$ fc-list :charset=e68b
/usr/share/fonts/truetype/libreoffice/opens___.ttf: OpenSymbol:style=Regular
/home/baco/.local/share/fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf: Symbols Nerd Font Mono:style=Regular
```

vs:
```
$ fc-list :charset=e7a8
/home/baco/.local/share/fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf: Symbols Nerd Font Mono:style=Regular
```
