### ISSUE TITLE
Create a category for icons from desktop environments and window managers

### ISSUE THREAD

**Issue by hasecilu** [nvim-tree/nvim-web-devicons#432]
On https://github.com/lukas-w/font-logos projects there are a few logos that some developers/users may find useful.

Currently there is only a category for OSs.

### Desktop Environments

| Name | svg | comment |
|---|---|---|
| Cinnamon | cinnamon | DE |
| Gnome | gnome | Org 4 DE
| LXDE | lxde |  DE |
| LXQt | lxqt |  DE |
| MATE | mate |  DE |
| Wayland | wayland | Protocol
| XFCE | xfce |  DE |
| Xorg | xorg | Org 4 X Window System

### Window Managers / Compositors

| Name | svg | comment |
|---|---|---|
| Awesome WM | awesome |  WM |
| bspwm | bspwm | WM |
| dwm | dwm | WM |
| Enlightenment | enlightenment | WM |
| Fluxbox | fluxbox | WM |
| Hyprland | hyprland | WM |
| i3 | i3 | WM |
| JWM | jwm | WM |
| Qtile | qtile | WM |
| Sway | sway | WM |
| XMonad | xmonad | WM |

**Comment by alex-courtis** [comment]
Sounds good! Please add new sections for `:NvimWebDeviconsHiTest`

I am going to ask for a river WM icon ;)

**Comment by hasecilu** [comment]
This is cool!
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/53124818/5c480c58-4043-496c-8276-2284113b40f6)
