### ISSUE TITLE
Cannot override some icons by filename

### ISSUE THREAD

**Issue by Poly2it** [nvim-tree/nvim-web-devicons#434]
I have tried overriding the `LICENSE` and `README` file icons by filename, but they simply don't function. How do I override these? Here is the relevant configuration:

```lua
{
	color_icons = true,
	default = false,
	strict = true,
	override_by_filename = {
		["README"] = {
			icon = "",
			color = colors.light_2,
			name = "Readme",
		},
		["LICENSE"] = {
			icon = "",
			color = colors.yellow_3,
			name = "License",
		},
	},
}
```

**Comment by Poly2it** [comment]
I am also unable to override the "png" icon by filetype.

**Comment by Poly2it** [comment]
Sometimes I also have to restart Neovim as some icons in the table are not applied at random.

**Comment by Poly2it** [comment]
There were no configuration changes between the capturings of these two screenshots. 
![example_1](https://github.com/nvim-tree/nvim-web-devicons/assets/84731064/a5c0c8a1-55d5-47a3-a56b-1d6b7b77cb61)
![example_0](https://github.com/nvim-tree/nvim-web-devicons/assets/84731064/5f14e071-fa1f-4a89-9a3b-428baaa21659)

**Comment by Poly2it** [comment]
I wrote my own custom API-compatible icon plugin to resolve the bugs: https://github.com/Poly2it/nvim/tree/master/lua/modules/salt-icons.

**Comment by alex-courtis** [comment]
Are you using the lazy plugin manager? It's startup ordering is unpredictably deterministic.

Most usages of web-devicons do cache icons, hence startup order is important.

**Comment by Poly2it** [comment]
> Are you using the lazy plugin manager? It's startup ordering is unpredictably deterministic.
> 
> Most usages of web-devicons do cache icons, hence startup order is important.

Yes, do I close as unsupported?

**Comment by alex-courtis** [comment]
> Yes, do I close as unsupported?

In that case, try to ensure that lazy executes nvim-web-devicons setup before the other plugins that use it.

Alternatively you can try a deterministic plugin manager.

Closing, please do reply with your solution if that works for you.
