### ISSUE TITLE
TeX icon incorrect

### ISSUE THREAD

**Issue by chardoncs** [nvim-tree/nvim-web-devicons#435]
Currently, the TeX file type maps to this icon:

<img width="50" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/44740171/715e3acf-5e9d-4858-897e-b3281abff292">

But I have checked the cheatsheet and the icon mapping seems not right.

<img width="108" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/44740171/161527c3-8d13-4354-b916-1fc6ac7ea3b4">

The correct icon should be this:

<img width="126" alt="image" src="https://github.com/nvim-tree/nvim-web-devicons/assets/44740171/711d5e4b-aa14-4dfc-9c4e-16cfcf1bde57">

I don't know if this also happens on others' computers or just mine.

**Comment by hasecilu** [comment]
This is how it looks changed
 - 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/53124818/6489bda1-ae8c-4fae-a08a-9bbfbd383dc9)

**Comment by chardoncs** [comment]
> This is how it looks changed  -

I think I know what you mean. I just checked the source code. And I found both `plaintex` (I guess it's plain text) and `tex` map to `tex`.

lua/nvim-web-devicons.lua - 173

```lua
["plaintex"] = "tex",
```

lua/nvim-web-devicons.lua - 223

```lua
["tex"] = "tex",
```

**Comment by chardoncs** [comment]
Okay, I actually don't know what you mean... It looks like `tex` is not `t.tex`...

Btw I have located the source code causing this issue.
