### ISSUE TITLE
[QUESTION]: how to add custom icon to laravel blade files

### ISSUE THREAD

**Issue by itsmenewbie03** [nvim-tree/nvim-web-devicons#439]
Currently laravel blade files are displayed with the same icon as php.
However it would be nice if they could be customized to have the laravel logo instead.

This is how it currently looks like
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/89230263/b1c2a7ba-b358-4174-9a8e-2ecaf3d99e7a)
An icon is available that could be a good replacement
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/89230263/337b03d8-7490-44cd-8f62-20712f94a67d)

**Comment by hasecilu** [comment]
Use `blade.php` as extension

**Comment by itsmenewbie03** [comment]
Thanks

**Comment by itsmenewbie03** [comment]
> [Pull Request](https://github.com/nvim-tree/nvim-web-devicons/blob/master/CONTRIBUTING.md) are always gratefully appreciated.

#442
