### ISSUE TITLE
Invalid highlight name 

### ISSUE THREAD

**Issue by hyde-stevenson** [nvim-tree/nvim-web-devicons#440]
Hello, 

I updated this morning my plugins, and now I get : 
```

Failed to run `config` for nvim-tree.lua

...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:286: Invalid highlight name: 'DevIconTrisquel_GNU-Linux
```
And sometimes I got the same message with : `Invalid highlight name: 'DevIconParabola_GNU-Linux_libre'`

Any idea ?

**Comment by dannyk3941** [comment]
I'm also getting similar error aftering updating plugins with lazy.vim

<img width="942" alt="Screenshot 2024-04-09 at 5 33 01 PM" src="https://github.com/nvim-tree/nvim-web-devicons/assets/52807859/f3ccdae8-bd85-46f4-a7a5-7b43fdc168f7">

Not sure where to go from here

**Comment by adjioev** [comment]
Same issue, below is the full message:


E5248: Invalid character in group name
E5108: Error executing lua ...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:286: Invalid highlight name: 'DevIconParabola_GNU-Linux_libre'
stack traceback:
	[C]: in function 'nvim_set_hl'
	...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:286: in function 'set_up_highlight'
	...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:314: in function 'set_up_highlights'
	...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:410: in function 'setup'
	...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:470: in function 'get_icon'
	.../nvim/lazy/bufferline.nvim/lua/bufferline/utils/init.lua:205: in function 'get_icon'
	...hare/nvim/lazy/bufferline.nvim/lua/bufferline/models.lua:168: in function 'new'
	...are/nvim/lazy/bufferline.nvim/lua/bufferline/buffers.lua:66: in function 'get_components'
	...local/share/nvim/lazy/bufferline.nvim/lua/bufferline.lua:56: in function <...local/share/nvim/lazy/bufferline.nvim/lua/bufferline.lua:54>
	[C]: in function 'ui_attach'
	.../.local/share/nvim/lazy/noice.nvim/lua/noice/ui/init.lua:74: in function 'enable'
	...oev/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:61: in function 'enable'
	...oev/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:23: in function <...oev/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:19>
	[C]: in function 'xpcall'
	...local/share/nvim/lazy/noice.nvim/lua/noice/util/call.lua:149: in function 'try'
	...oev/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:19: in function <...oev/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:18>

**Comment by tp86** [comment]
Same here, I believe it's because of dashes in icon names introduced in https://github.com/nvim-tree/nvim-web-devicons/pull/433

**Comment by hasecilu** [comment]
Hi, when I made that change originally I used `/` in the names and and received that same error so I changed the `/` for the `-` and didn't get error, just tested maaster again and don't have problem, I'm using Alacritty.

**Comment by hasecilu** [comment]
That would be strange, or could be also the `_`? I'm looking at the code and seems no other names are using `_` or `-`.
I use LazyVim that uses Neotree that uses nvim-web-devicons, not sure if that's relevant.

**Comment by meatballs** [comment]
I'm seeing this on both kitty and gnome terminal on Ubuntu

**Comment by hasecilu** [comment]
I'll remove both `-` and `_`

**Comment by GianlucaP106** [comment]
Same issue here

**Comment by wyankx** [comment]
Same issue

**Comment by oldtune** [comment]
having same issue with DevIconLoc-OS

**Comment by hasecilu** [comment]
Could you try to update to Neovim 0.9.5 and see if the problem remains?  https://github.com/nvim-tree/nvim-web-devicons/pull/441#issuecomment-2045527259

**Comment by henry-hsieh** [comment]
I have tested on Neovim v0.9.4 and v0.9.5. The v0.9.4 has these errors, but v0.9.5 not.

**Comment by GianlucaP106** [comment]
I have also updated to nvim v0.9.5 and this solved the problem. Same conclusion as @henry-hsieh

**Comment by hyde-stevenson** [comment]
Yeah the upgrade fixed it :)
