### ISSUE TITLE
W18 invalid character in a group name 

### ISSUE THREAD

**Issue by VynceCook** [nvim-tree/nvim-web-devicons#446]
Hello,

I have an error when opening vim:

![Capture d’écran du 2024-04-19 12-34-43](https://github.com/nvim-tree/nvim-web-devicons/assets/1019987/72705f7f-2fae-48f0-b34f-96fe13e74cd6)

When I comment out the web-devicons package, the error disappears but I no longer have the icons in my lualine bar:

`
 "   Plug 'nvim-tree/nvim-web-devicons'  " If you want to have icons in your statusline choose one of these
`

Here is the extract from the log file that allowed me to see that the error came from web-devicons. Unfortunately there isn't much information about where the error came from.

```
chdir(/home/vincent)
chdir(/home/vincent/.local/share/nvim/site/plugged/nvim-web-devicons/lua)
chdir(/home/vincent)
                    W18: Caractère invalide dans un nom de groupe
chdir(/home/vincent)
chdir(/home/vincent/.local/share/nvim/site/plugged/nvim-web-devicons/lua)
chdir(/home/vincent)
```

I use NVIM v0.7.2.

Have you encountered this problem before?

**Comment by gegoune** [comment]
Neovim 0.7.2 is almost two years old. I would suggest you try newer version, ideally latest stable, which definitely is supported by this plugin.

We say in readme [neovim >=0.7.0](https://github.com/neovim/neovim/wiki/Installing-Neovim), but perhaps there were changes that broke that requirement without updating readme.

**Comment by VynceCook** [comment]
I have upgraded nvim to a newer version and it works. Thanks a lot.
