### ISSUE TITLE
FR: differentiate `.d.ts` from `.ts` files (typescript)

### ISSUE THREAD

**Issue by chrisgrieser** [nvim-tree/nvim-web-devicons#452]
A small but useful improvement would be to differentiate regular typescript files (`.ts`) from typescript declaration files (`.d.ts`)

**Comment by alex-courtis** [comment]
That would be great; [pull requests](https://github.com/nvim-tree/nvim-web-devicons/blob/master/CONTRIBUTING.md) are gratefully appreciated.

**Comment by chrisgrieser** [comment]
Yeah, I already contributed a few icons, but tbh, I am not fully sure how prioritization works here, with file endings like `.d.ts` also ending in `.ts`.

**Comment by alex-courtis** [comment]
> Yeah, I already contributed a few icons, but tbh, I am not fully sure how prioritization works here, with file endings like `.d.ts` also ending in `.ts`.

Give it a go and see...
