### ISSUE TITLE
Gulpfile and Gruntfile incorrect icon

### ISSUE THREAD

**Issue by RafaelAntonny** [nvim-tree/nvim-web-devicons#456]
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/14ab7a96-c349-4ba4-9cf7-1e4c29109913)

I'm using Lazy as my package manager devicons is a dependency for these following plugins that I have downloaded lualine, telescope and nvim-tree.
I already did a set_icon() for gulp I was able to change the icon but I wasn't able to change the color. 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/0d21818b-2b09-4fcc-87a0-fcc0622395fd)
this is the result when I do a get_icon and a print
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/76e9415d-b316-497e-8ade-1dba436bddc8)
I already tried to make devicons load faster by putting it in a after/plugins folder which did make it load ahead of the plugins that are dependant on devicons but that didn't fix my problem, the icon is still the JS icon.

**Comment by alex-courtis** [comment]
[Lazy loading](https://github.com/nvim-tree/nvim-tree.lua/wiki/Installation#lazy-loading) is problematic.

Please try and reproduce using the minimal nvim-tree bug report template as per https://github.com/nvim-tree/nvim-web-devicons/issues/455#issuecomment-2081716098

**Comment by RafaelAntonny** [comment]
Like just setup({}) for nvim-tree right ? I just did that nothing has changed 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/59c85400-df36-48c3-bb01-278f413a1f24)
Also, my mistake, its not only nvim-tree that is having the problem with the incorrect icons telescope, bufferline (didn't mention before because I forgot) are also having that problem, I don't use the file icons for lualine so I cannot tell if its having the same issue but ig its a safe bet to say it does.
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/f1d3e52e-097f-4f1c-be2f-5f8eaa79686a)
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/87d9b795-5f21-414e-9858-bbd769a59cb8)
I did try override the icon again a little earlier, it did work with the colors and everything but only after I changed from 'gulpfile' to 'gulpfile.js'

**Comment by RafaelAntonny** [comment]
I forgot to mention, after you pointed out the lazy loading I turned lazy loading for all of these plugins that are dependant on devicon to see if any of them were interfering with devicons loading, no success there

**Comment by alex-courtis** [comment]
There's a lot going on there; please try a minimal config without lazy.

**Comment by RafaelAntonny** [comment]
Sorry for the delay, was figuring out how to install plugins with packer lol.
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/d6fb69f7-87b9-4b99-9884-175910069adb)
this is packer, minimal neovim install

**Comment by alex-courtis** [comment]
> this is packer, minimal neovim install

Excellent. Please share so that we can reproduce.

**Comment by RafaelAntonny** [comment]
aye, [this repo here has the files](https://github.com/RafaelAntonny/dot-file-issuel) if it isn't a problem

**Comment by alex-courtis** [comment]
> aye, [this repo here has the files](https://github.com/RafaelAntonny/dot-file-issue) if it isn't a problem

Sorry, I'm not going to debug your configuration.

Minimal configuration as requested please. We'll be mandating that soon: #457

**Comment by RafaelAntonny** [comment]
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/b603ec01-9478-4a8d-a822-68368801f163)
```lua
for name, url in pairs{
  devicons = 'https://github.com/nvim-tree/nvim-web-devicons',
  nvimtree = 'https://github.com/nvim-tree/nvim-tree.lua',
} do
  local install_path = vim.fn.fnamemodify('devicons_issue'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('nvim-web-devicons').setup{}
require('nvim-tree').setup()
```
first time opening an issue, I apologize if I am being hard to work with

**Comment by alex-courtis** [comment]
Don't stress, you're fine. We need to add our bug report template.

I like the minimal; that sounds like what we should use.

It looks to be working as intended: gulpfile and gruntfile files show their icons:
![20240430_135208](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/562e9ac5-ad1a-49aa-a34d-950d547def6c)

Are those names correct?

**Comment by RafaelAntonny** [comment]
interesting so it only works if it doesn't have the .js extension, hmm...
well the name is correct but the .js extension is nescessary
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/090ef7e4-87ac-482b-887b-dd47ac2e8514)
otherwise npm can't run it 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/100977778/d596deeb-fd79-4b32-932d-55fe8ef3fb4c)

You think this is an appropriate point to close the issue ?

**Comment by alex-courtis** [comment]
Sounds like they're incorrect... [pull requests](https://github.com/nvim-tree/nvim-web-devicons/blob/master/CONTRIBUTING.md) are gratefully appreciated.
