### ISSUE TITLE
Cannot override Lua icon color

### ISSUE THREAD

**Issue by ThaiDuy12345** [nvim-tree/nvim-web-devicons#462]
My configuration:
```
devicons.setup({
      -- NOTE: override the icon
      override_by_extension = {
        java = { icon = "", color = "#e46368", name = "Java" },
        [".gitignore"] = { icon = "", color = "#428850", name = "GitIgnore" },
        js = { icon = "", color = "#f7cd6d", name = "JavaScript" },
        json = { icon = "", color = "#f7cd6d", name = "JSON" },
        ts = { icon = "󰛦", color = "#87b2e2", name = "TypeScript" },
        html = { icon = "", color = "#de7558", name = "Html" },
        rb = { icon = "", color = "#ef757c", name = "Rb" },
        rake = { icon = "", color = "#ef757c", name = "Rake" },
        rakefile = { icon = "", color = "#ef757c", name = "RakeFile" },
        jbuilder = { icon = "", color = "#f7cd6d", name = "Jbuilder" },
        lua = { icon = "", color = "#37c88e", name = "Lua" }
      },
      color_icons = true,
      default = false,
      strict = true,
})
```
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/103923561/994c258e-405e-4391-a1a3-d58fb4b3c42c)
NvimTree:
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/103923561/83089e61-fb83-434a-ac23-384696118de0)

I expected the DevIconLua should be green as same as the highlight color you guys can see in the photo but it's still have the default color. Other icons seem work fine.

**Comment by alex-courtis** [comment]
Execute `setup` for web-devicon before you execute nvim-tree setup.

What's that plugin that shows the rgb colours after the `#`? That looks incredibly useful!

![20240514_090008](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/317e2ec9-2ed2-4be6-a9cb-ff12dee299a9)

**Comment by alex-courtis** [comment]
Raised #464

Added to readme: https://github.com/nvim-tree/nvim-web-devicons?tab=readme-ov-file#my-setup-overrides-are-not-applied

**Comment by ThaiDuy12345** [comment]
> Execute nvim-web-devicons `setup` before you execute nvim-tree setup.
> 
> What's that plugin that shows the rgb colours after the `#`? That looks incredibly useful!
> 
> ![20240514_090008](https://private-user-images.githubusercontent.com/1505378/330225698-317e2ec9-2ed2-4be6-a9cb-ff12dee299a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjU2NTQsIm5iZiI6MTcxNTY2NTM1NCwicGF0aCI6Ii8xNTA1Mzc4LzMzMDIyNTY5OC0zMTdlMmVjOS0yZWQyLTRiZTYtYTljYi1mZjEyZGVlMjk5YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMDU0MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMxYjAzZGY4NTlhODM3ZGVkZDVmODRlMDBjNjhjOTgxYjNiZWEzZGQwNGVmZDYyN2Q4Njg3MmQ0NDM1MzgzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MIev0raPVdsB-FNUS8W0LS5czLQJGo0csa3AfZyIJFk)

Thanks for the fast response!! 😊 it's from https://github.com/brenoprata10/nvim-highlight-colors

**Comment by ThaiDuy12345** [comment]
> Execute nvim-web-devicons `setup` before you execute nvim-tree setup.
> 
> What's that plugin that shows the rgb colours after the `#`? That looks incredibly useful!
> 
> ![20240514_090008](https://private-user-images.githubusercontent.com/1505378/330225698-317e2ec9-2ed2-4be6-a9cb-ff12dee299a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjU2NTQsIm5iZiI6MTcxNTY2NTM1NCwicGF0aCI6Ii8xNTA1Mzc4LzMzMDIyNTY5OC0zMTdlMmVjOS0yZWQyLTRiZTYtYTljYi1mZjEyZGVlMjk5YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMDU0MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMxYjAzZGY4NTlhODM3ZGVkZDVmODRlMDBjNjhjOTgxYjNiZWEzZGQwNGVmZDYyN2Q4Njg3MmQ0NDM1MzgzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MIev0raPVdsB-FNUS8W0LS5czLQJGo0csa3AfZyIJFk)

I added these property to the plugin which expected Lazy.nvim will load and setup it first, but still didnt work....Not only my nvim-tree, but also bufferline-nvim or incline-nvim and maybe other plugin did not catch the color

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/103923561/87db6195-a5fb-43d7-bde2-5749dc847ad1)

Incline-nvim: 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/103923561/105fcec5-f70a-48bc-9a31-5328e979a5b1)

bufferline: 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/103923561/edb9b64f-131a-4942-a141-449f1a38205a)

**Comment by ThaiDuy12345** [comment]
UPDATE:

I have got the DevIconLua to change the color, but I have to do an extra line of code after the setup method:

 ```
 devicons.set_icon({
      java = { icon = "", color = "#e46368", name = "Java" },
      [".gitignore"] = { icon = "", color = "#428850", name = "GitIgnore" },
      js = { icon = "", color = "#f7cd6d", name = "JavaScript" },
      json = { icon = "", color = "#f7cd6d", name = "JSON" },
      ....
 })
 ```
 Dont really know why but it work for me for now
 
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/103923561/ed2929ea-cf52-4a86-9e60-d12dc4b599cb)

**Comment by alex-courtis** [comment]
Great news!

#464 should resolve these sorts of problems.

**Comment by ThaiDuy12345** [comment]
> Great news!
> 
> #464 should resolve these sorts of problems.

Cool, will try this out

**Comment by mawkler** [comment]
@alex-courtis 

> Great news!
>
> #464 should resolve these sorts of problems.

#464 seems to be an issue, not a PR. Is there any PR that solves this that I can try out?

---

I'm having a similar issue where _sometimes_ the color of the override is set to white, even though I've set some other color.

Here's a minimal config that reproduces the issue:

<details>
<summary><b>Click to expand</b></summary>

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
vim.fn.system({
  'git',
  'clone',
  '--filter=blob:none',
  'https://github.com/folke/lazy.nvim.git',
  '--branch=stable', -- latest stable release
  lazypath,
})
end
vim.opt.rtp:prepend(lazypath)

vim.keymap.set('n', '<c-q>', vim.cmd.quit)

require('lazy').setup({
  {
    'nvim-tree/nvim-web-devicons',
    opts = {
      override = {
        md = {
          icon = 'THIS TEXT IS SOMETIMES WHITE',
          color = 'red', -- The text should be red, not white
          name = 'Markdown'
        },
      },
    }
  },
  {
    'romgrk/barbar.nvim',
    dependencies = 'nvim-tree/nvim-web-devicons',
    opts = {},
  }
})
```

</details>

**To reproduce**

1. Open a markdown file with `nvim -u path/to/config/above`
2. The text `THIS TEXT IS SOMETIMES WHITE` is sometimes white, and sometimes red (which it should be)

The issue seems to occur with about a 50% chance.

**Comment by alex-courtis** [comment]
> I'm having a similar issue where _sometimes_ the color of the override is set to white, even though I've set some other color.

Sometimes is the key. Lazy's ordering is nondeterministic.

Can you try with another plugin manager or call setup yourself afterwards, in the correct order?
