### ISSUE TITLE
set_icon not work

### ISSUE THREAD

**Issue by minhanghuang** [nvim-tree/nvim-web-devicons#465]
I tried to change `launch` file icon, but it seems that the changes has not taken effect, the previous changes were not a problem and I don't know from which version the problem started

```shell
system: Ubuntu20.04 docker container
Neovim: 0.10.0 stable
nvim-web-devicons: 11eb26fc166742db8d1e8a6f5a7de9df37b09aae
nvim-tree.lua: 76db7ed0da3027882dd0a72de18643c2e26956dc(branch: nvim-tree-v1.3.1)
```

```lua
local has_web_devicons, web_devicons = pcall(require, "nvim-web-devicons")
if not has_web_devicons then
  vim.notify("nvim-web-devicons not found!")
  return
end

local my_icons = {
  ["inl"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "Hpp"
  },
  ["urdf"] = {
    icon = "謹",
    color = "#e37933",
    cterm_color = "173",
    name = "Xml",
  },
  ["xodr"] = {
    icon = "謹",
    color = "#e37933",
    cterm_color = "173",
    name = "Xml",
  },
  ["cu"] = {
    icon = "",
    color = "#f34b7d",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["launch"] = {
    icon = "謹",
    color = "#e37933",
    cterm_color = "173",
    name = "Xml",
  },
}

if web_devicons.has_loaded then
  web_devicons.set_icon(my_icons)
else
  web_devicons.setup({ override = my_icons, default = true })
end
```

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/37317982/b688a77e-34a8-40e9-9183-79296925280a)

**Comment by minhanghuang** [comment]
I will switch `nvim-web-devicons` back to historical commit `2d02a56` and it will be resolved
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/37317982/2b6bfcd8-f295-409e-a23e-d29bceff2d9e)

**Comment by alex-courtis** [comment]
Thanks for the detailed report.

I'd be most grateful if you could test this fix:

```sh
cd /path/to/nvim-web-devicons
git pull
git checkout 465-set_icon-broken
```

When you're finished testing:
```sh
git checkout master
```

**Comment by minhanghuang** [comment]
Ok, tested it, works like a charm! thank you very much!
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/37317982/aa0d63a5-06f3-4aca-92a3-a0cb9317f855)
