### ISSUE TITLE
Cannot install nvim-web-devicons properly on Nvim 0.7.2

### ISSUE THREAD

**Issue by MinhTran0911** [nvim-tree/nvim-web-devicons#467]
I try to install nvim-web-devicons using Packer on Nvim 0.7.2 (cannot upgrade to newer Nvim version due to machine limitation):
```
use {'nvim-tree/nvim-web-devicons'}
```
As soon as I run ```:PackerSync``` to install it, this message appears everytime I open Nvim:
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/56530177/ae78f454-e8f4-408e-813e-42f8d2caa50e)

Line 26 of my init.vim contains the end marker for LUA section - EOF:
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/56530177/d33ee299-2f4f-4f1c-b8ed-6ba943809b8b)

Note that the problem appears even when I don't call ```require('nvim-web-devicons').setup()```.
Also, I cannot run ```:NvimWebDeviconsHiTest```, as the following stacktrace:
![image](https://github.com/nvim-tree/nvim-web-devicons/assets/56530177/80a4edc3-7ec3-4575-bd7a-9afd0f7079bd)

Any help would be appreciated!

**Comment by gegoune** [comment]
0.7.2 is pretty dated, and although we state in documentation (https://github.com/nvim-tree/nvim-web-devicons?tab=readme-ov-file#requirements) that we are supporting this version it clearly isn't the case. We should update documentation @alex-courtis (I suggest we support 0.9 and, 0.10 and nightly)

Out of interest, what's your machine limitation prohibiting you from upgrading?

**Comment by MinhTran0911** [comment]
My company's server is running on a very dated OS, so new versions of Nvim cannot run due to GLIBC version being old. Compiling Nvim from source is also not an option because the gcc toolkit is outdated too -> Install newer gcc and a thousand of its dependencies is a pain (have to find out which version can run on my version of GLIBC). And no internet connection due to privacy reasons, so there's that ... .
Anw, thank you for your prompt response.
