### ISSUE TITLE
Make files in `diagnostics` use `TroubleFileName` color

### ISSUE THREAD

**Issue by GrzegorzKozub** [nvim-tree/nvim-web-devicons#474]
Would it be possible to highlight file names in `diagnostics` with `TroubleFileName`, similar to `symbols`? Currently they seem to be highlighted by `TroubleNormal`.

![image](https://github.com/nvim-tree/nvim-web-devicons/assets/154056/4e25c724-4829-400f-aa80-50d949a65aae)

**Comment by gegoune** [comment]
Posted in wrong repository? We have no control over how trouble.nvim highlight icons.

**Comment by GrzegorzKozub** [comment]
Man :) Sorry for that.
