### ISSUE TITLE
Warning while using barbar

### ISSUE THREAD

**Issue by TriupLauro** [nvim-tree/nvim-web-devicons#489]
I have a warning when starting vim, as explained [here](https://github.com/romgrk/barbar.nvim/issues/595).

Following the barbar devs answer, I disabled icons after removing nvim-web-devicons.

The warning then stopped.

Which version should I be using to avoid the warning on startup.

Even with warning, icons are actually displayed in the tab bar with barbar.

NB : 

this is the output of nvim --version

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilé par team+vim@tracker.debian.org
```

Thanks in advance

**Comment by hasecilu** [comment]
I'm not sure which is the minimal version but try with latest stable. #446

**Comment by TriupLauro** [comment]
It seems I'm already using the latest stable for my distro.

Nvim is not listed in the `apt list --upgradable` output.

Can I use a different version of nvim-web-devicons ?

**Comment by hasecilu** [comment]
Personally, I use the latest version on my Debian server from [release page](https://github.com/neovim/neovim/releases/tag/v0.10.1). I followed the instructions for the appimage file, also I created a symlink to the appimage on `/usr/bin`; it's a shame they stopped creating `deb` packages.

Don't let your distro's packaging decisions affect your workflow, fortunately we have options to upgrade.

**Comment by alex-courtis** [comment]
Debian lagging is unfortunate. Some users have similar issues with some ubuntu distros. The solution for them was also to pull the binary as above.
