### ISSUE TITLE
Capital 'R' file extension not recognized

### ISSUE THREAD

**Issue by PMassicotte** [nvim-tree/nvim-web-devicons#505]
Related to this: https://github.com/nvim-tree/nvim-web-devicons/discussions/504

It seems that icon for the R language is not properly retrieved because file extension is usually referred with `.R` and not `.r`.  In `nvim-tree`, this is not rendering the icon properly. 

![image](https://github.com/user-attachments/assets/91e810f3-0f75-4f3f-8041-fa859251394b)

I am not too sure which of `nvim-tree` or `nvim-web-devicons` should handle this.

I am using the latest version of both plugins.

**Comment by alex-courtis** [comment]
It looks like extension `foo.R` was previously being matched by filename `R`, which was an unwanted side-effect.

Adding the missing explicit `R` extension entry should fix this.

**Comment by alex-courtis** [comment]
Should be fixed on master, please advise if it's not working @PMassicotte

**Comment by PMassicotte** [comment]
I confirm it is working. Thank you very much for this.
