### ISSUE TITLE
Gemfile ruby icon is not used due to wrong definition

### ISSUE THREAD

**Issue by volodymyr-vt** [nvim-tree/nvim-web-devicons#510]
![image](https://github.com/user-attachments/assets/e4c8e456-e604-4ebe-a96c-d772f4878903)
Gemfile ruby icon is not used due to wrong definition `"gemfile$"` here:
https://github.com/nvim-tree/nvim-web-devicons/blob/19d257cf889f79f4022163c3fbb5e08639077bd8/lua/nvim-web-devicons/icons-light.lua#L464C4-L464C14
```
  ["gemfile$"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Gemfile",
  },
```
However if i manually create new definition in my nvim config that uses `   ["Gemfile"] = {` instead of `["gemfile$"] = {` it works.

**Comment by alex-courtis** [comment]
Looking back it appears that this is incorrect. It's trying to use `gemfile$` as a regex. Regex matching is not a feature for performance reasons.

# Fix 1

File named exactly `gemfile` will match the ruby icon. It is case insensitive.

# Fix 2

I don't know ruby. Is gemfile used as an extension, something like `myproject.gemfile`?

If so, we can add that as an extension as well.

**Comment by volodymyr-vt** [comment]
> I don't know ruby. Is gemfile used as an extension, something like `myproject.gemfile`?

Gemfile is just plain text file with ruby code and name `Gemfile`.  It's the same as  `Dockerfile`.

Hovever Dockerfile defined like this:
```
 ["Dockerfile"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
```
So we need to change `Gemfile` definition to the following:
```
  ["Gemfile"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Gemfile",
  },
  ```
  
  I can make a PR with fix.

**Comment by alex-courtis** [comment]
That's right; PR would be most gratefully appreciated.
