### ISSUE TITLE
The repo description should state what the plugin does rather than just stating its a fork

### ISSUE THREAD

**Issue by Oneechan69** [nvim-tree/nvim-web-devicons#516]
I had made a [discussion post](https://github.com/nvim-tree/nvim-web-devicons/discussions/508) and one [on Reddit](https://new.reddit.com/r/neovim/comments/1gix7m2/overriding_specific_nerd_icons_in_nvimwebdevicons/) asking how to override individual nvim-web-icons, mistakenly thinking that it serves any nerd font icon, and only found out recently that the plugin is specifically for filetype icons. I think the repo description should change to something like "A plugin for serving filetype icons, forked from vim-devicons"

**Comment by hasecilu** [comment]
Agree with the need of change but I don't understand how the current description misleaded you to think that was possible.

**Comment by Oneechan69** [comment]
I didn't check the repo of vim-devicons.

**Comment by alex-courtis** [comment]
Please review @Oneechan69 :  #517
